plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'io.lunararcdevs.lunararc'
version = '1.2.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    api 'org.jetbrains:annotations:24.1.0'

    compileOnly 'io.papermc.paper:paper-api:26.2.build.128-stable'
    compileOnly 'org.ow2.asm:asm:9.10.1'
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

compileJava {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
